# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope.platform.tasks.analysis import dataframe_count as dataframe_count
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import get_events as get_events
from ecoscope.platform.tasks.io import (
    get_patrol_observations as get_patrol_observations,
)
from ecoscope.platform.tasks.io import get_patrols as get_patrols
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.io import (
    unpack_events_from_patrols_df as unpack_events_from_patrols_df,
)
from ecoscope.platform.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import create_path_layer as create_path_layer
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_map as draw_map
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    concat_dataframes as concat_dataframes,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_belize.tasks import (
    apply_qualitative_color_map as apply_qualitative_color_map,
)
from ecoscope_workflows_ext_belize.tasks import (
    assemble_patrol_summary as assemble_patrol_summary,
)
from ecoscope_workflows_ext_belize.tasks import (
    assemble_vessels_by_category as assemble_vessels_by_category,
)
from ecoscope_workflows_ext_belize.tasks import (
    assemble_vessels_documented as assemble_vessels_documented,
)
from ecoscope_workflows_ext_belize.tasks import (
    draw_bar_chart_colored as draw_bar_chart_colored,
)
from ecoscope_workflows_ext_belize.tasks import (
    drop_skipped_layers as drop_skipped_layers,
)
from ecoscope_workflows_ext_belize.tasks import (
    explode_commercial_fishing_fishers as explode_commercial_fishing_fishers,
)
from ecoscope_workflows_ext_belize.tasks import (
    filter_events_by_patrol_linkage as filter_events_by_patrol_linkage,
)
from ecoscope_workflows_ext_belize.tasks import (
    filter_observations_by_patrol_id as filter_observations_by_patrol_id,
)
from ecoscope_workflows_ext_belize.tasks import (
    filter_patrols_by_id as filter_patrols_by_id,
)
from ecoscope_workflows_ext_belize.tasks import (
    filter_recreational_vessels_by_category as filter_recreational_vessels_by_category,
)
from ecoscope_workflows_ext_belize.tasks import (
    fit_view_to_geodataframes as fit_view_to_geodataframes,
)
from ecoscope_workflows_ext_belize.tasks import (
    flatten_commercial_fishing_vessels as flatten_commercial_fishing_vessels,
)
from ecoscope_workflows_ext_belize.tasks import (
    gather_belize_dashboard as gather_belize_dashboard,
)
from ecoscope_workflows_ext_belize.tasks import (
    generate_belize_patrol_report as generate_belize_patrol_report,
)
from ecoscope_workflows_ext_belize.tasks import (
    get_report_generated_by as get_report_generated_by,
)
from ecoscope_workflows_ext_belize.tasks import set_color_palette as set_color_palette
from ecoscope_workflows_ext_belize.tasks import (
    set_optional_string_var as set_optional_string_var_1,
)
from ecoscope_workflows_ext_belize.tasks import (
    tag_commercial_vessel_category as tag_commercial_vessel_category,
)
from ecoscope_workflows_ext_belize.tasks import (
    tag_recreational_vessel_category as tag_recreational_vessel_category,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    download_event_attachments as download_event_attachments,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%b %-d, %Y %-I:%M %p", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    base_maps = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_maps") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params.get("groupers") or {}))
        .call()
    )

    patrol_id_filter = (
        task(set_optional_string_var_1)
        .validate()
        .set_task_instance_id("patrol_id_filter")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("patrol_id_filter") or {}))
        .call()
    )

    plot_palette = (
        task(set_color_palette)
        .validate()
        .set_task_instance_id("plot_palette")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("plot_palette") or {}))
        .call()
    )

    patrols = (
        task(get_patrols)
        .validate()
        .set_task_instance_id("patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            patrol_types=[],
            status=None,
            sub_page_size=100,
            patrols_overlap_daterange=True,
            raise_on_empty=False,
            **(params.get("patrols") or {}),
        )
        .call()
    )

    patrols_filtered = (
        task(filter_patrols_by_id)
        .validate()
        .set_task_instance_id("patrols_filtered")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=patrols,
            patrol_id=patrol_id_filter,
            **(params.get("patrols_filtered") or {}),
        )
        .call()
    )

    patrol_linkage = (
        task(unpack_events_from_patrols_df)
        .validate()
        .set_task_instance_id("patrol_linkage")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=patrols_filtered,
            time_range=time_range,
            event_types=[],
            event_states=None,
            truncate_to_time_range=True,
            include_null_geometry=True,
            raise_on_empty=False,
            **(params.get("patrol_linkage") or {}),
        )
        .call()
    )

    patrol_observations = (
        task(get_patrol_observations)
        .validate()
        .set_task_instance_id("patrol_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            patrol_types=[],
            include_patrol_details=True,
            raise_on_empty=False,
            sub_page_size=100,
            patrols_overlap_daterange=True,
            **(params.get("patrol_observations") or {}),
        )
        .call()
    )

    patrol_observations_filtered = (
        task(filter_observations_by_patrol_id)
        .validate()
        .set_task_instance_id("patrol_observations_filtered")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_observations,
            patrols_df=patrols_filtered,
            patrol_id=patrol_id_filter,
            **(params.get("patrol_observations_filtered") or {}),
        )
        .call()
    )

    convert_patrol_obs_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_patrol_obs_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_observations_filtered,
            timezone=get_timezone,
            columns=["patrol_start_time", "patrol_end_time", "fixtime"],
            **(params.get("convert_patrol_obs_tz") or {}),
        )
        .call()
    )

    relocs = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=convert_patrol_obs_tz,
            relocs_columns=[
                "patrol_id",
                "patrol_type__display",
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("relocs") or {}),
        )
        .call()
    )

    trajs = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(relocations=relocs, **(params.get("trajs") or {}))
        .call()
    )

    trajectory_stats_by_patrol = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("trajectory_stats_by_patrol")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajs,
            groupby_cols=["extra__patrol_id"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "distance_km",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                    "decimal_places": 2,
                },
                {
                    "display_name": "duration_hours",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                    "decimal_places": 2,
                },
            ],
            **(params.get("trajectory_stats_by_patrol") or {}),
        )
        .call()
    )

    trajectory_stats = (
        task(map_columns)
        .validate()
        .set_task_instance_id("trajectory_stats")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajectory_stats_by_patrol,
            rename_columns={"extra__patrol_id": "patrol_id"},
            raise_if_not_found=False,
            retain_columns=None,
            drop_columns=None,
            duplicate_strategy="suffix",
            **(params.get("trajectory_stats") or {}),
        )
        .call()
    )

    patrol_details_events = (
        task(get_events)
        .validate()
        .set_task_instance_id("patrol_details_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            event_types=["patrol_details"],
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "serial_number",
                "event_details",
                "geometry",
            ],
            event_states=None,
            include_details=True,
            include_display_values=True,
            include_updates=False,
            include_related_events=False,
            force_point_geometry=True,
            include_null_geometry=True,
            raise_on_empty=False,
            **(params.get("patrol_details_events") or {}),
        )
        .call()
    )

    completion_log_events = (
        task(get_events)
        .validate()
        .set_task_instance_id("completion_log_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            event_types=["patrol_completion_log"],
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "serial_number",
                "event_details",
                "geometry",
            ],
            event_states=None,
            include_details=True,
            include_display_values=True,
            include_updates=False,
            include_related_events=False,
            force_point_geometry=True,
            include_null_geometry=True,
            raise_on_empty=False,
            **(params.get("completion_log_events") or {}),
        )
        .call()
    )

    recreational_vessel_events = (
        task(get_events)
        .validate()
        .set_task_instance_id("recreational_vessel_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            event_types=["recreational_vessels"],
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "serial_number",
                "event_details",
                "geometry",
            ],
            event_states=None,
            include_details=True,
            include_display_values=True,
            include_updates=False,
            include_related_events=False,
            force_point_geometry=True,
            include_null_geometry=False,
            raise_on_empty=False,
            **(params.get("recreational_vessel_events") or {}),
        )
        .call()
    )

    commercial_fishing_events = (
        task(get_events)
        .validate()
        .set_task_instance_id("commercial_fishing_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            event_types=["commercial_fishing_vessels_inspections"],
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "serial_number",
                "event_details",
                "geometry",
            ],
            event_states=None,
            include_details=True,
            include_display_values=True,
            include_updates=False,
            include_related_events=False,
            force_point_geometry=True,
            include_null_geometry=False,
            raise_on_empty=False,
            **(params.get("commercial_fishing_events") or {}),
        )
        .call()
    )

    recreational_events_filtered = (
        task(filter_events_by_patrol_linkage)
        .validate()
        .set_task_instance_id("recreational_events_filtered")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            events_df=recreational_vessel_events,
            patrol_linkage=patrol_linkage,
            event_type="recreational_vessels",
            patrol_id=patrol_id_filter,
            **(params.get("recreational_events_filtered") or {}),
        )
        .call()
    )

    commercial_events_filtered = (
        task(filter_events_by_patrol_linkage)
        .validate()
        .set_task_instance_id("commercial_events_filtered")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            events_df=commercial_fishing_events,
            patrol_linkage=patrol_linkage,
            event_type="commercial_fishing_vessels_inspections",
            patrol_id=patrol_id_filter,
            **(params.get("commercial_events_filtered") or {}),
        )
        .call()
    )

    patrol_table = (
        task(assemble_patrol_summary)
        .validate()
        .set_task_instance_id("patrol_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            patrols_df=patrols_filtered,
            patrol_details_events=patrol_details_events,
            completion_log_events=completion_log_events,
            patrol_linkage=patrol_linkage,
            trajectory_stats=trajectory_stats,
            **(params.get("patrol_table") or {}),
        )
        .call()
    )

    patrol_effort_summary = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("patrol_effort_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_table,
            groupby_cols=[],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "Number of Patrols",
                    "aggregator": "count",
                    "column": "patrol_id",
                    "decimal_places": None,
                },
                {
                    "display_name": "Distance (km)",
                    "aggregator": "sum",
                    "column": "distance_km",
                    "decimal_places": 2,
                },
                {
                    "display_name": "Number of Nights",
                    "aggregator": "sum",
                    "column": "nights",
                    "decimal_places": 0,
                },
                {
                    "display_name": "Number of Patrol Hours",
                    "aggregator": "sum",
                    "column": "duration_hours",
                    "decimal_places": 2,
                },
                {
                    "display_name": "Fuel Used (gal)",
                    "aggregator": "sum",
                    "column": "fuel_used_gal",
                    "decimal_places": 2,
                },
            ],
            **(params.get("patrol_effort_summary") or {}),
        )
        .call()
    )

    pes_patrols = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("pes_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_effort_summary,
            column_name="Number of Patrols",
            **(params.get("pes_patrols") or {}),
        )
        .call()
    )

    pes_patrols_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("pes_patrols_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Number of Patrols",
            decimal_places=0,
            data=pes_patrols,
            **(params.get("pes_patrols_sv") or {}),
        )
        .call()
    )

    pes_distance = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("pes_distance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_effort_summary,
            column_name="Distance (km)",
            **(params.get("pes_distance") or {}),
        )
        .call()
    )

    pes_distance_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("pes_distance_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Distance (km)",
            decimal_places=2,
            data=pes_distance,
            **(params.get("pes_distance_sv") or {}),
        )
        .call()
    )

    pes_nights = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("pes_nights")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_effort_summary,
            column_name="Number of Nights",
            **(params.get("pes_nights") or {}),
        )
        .call()
    )

    pes_nights_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("pes_nights_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Number of Nights",
            decimal_places=0,
            data=pes_nights,
            **(params.get("pes_nights_sv") or {}),
        )
        .call()
    )

    pes_hours = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("pes_hours")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_effort_summary,
            column_name="Number of Patrol Hours",
            **(params.get("pes_hours") or {}),
        )
        .call()
    )

    pes_hours_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("pes_hours_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Number of Patrol Hours",
            decimal_places=2,
            data=pes_hours,
            **(params.get("pes_hours_sv") or {}),
        )
        .call()
    )

    pes_fuel = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("pes_fuel")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_effort_summary,
            column_name="Fuel Used (gal)",
            **(params.get("pes_fuel") or {}),
        )
        .call()
    )

    pes_fuel_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("pes_fuel_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Fuel Used (gal)",
            decimal_places=2,
            data=pes_fuel,
            **(params.get("pes_fuel_sv") or {}),
        )
        .call()
    )

    staff_effort = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("staff_effort")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_table,
            groupby_cols=["leader"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "Number of Patrols",
                    "aggregator": "count",
                    "column": "patrol_id",
                    "decimal_places": None,
                },
                {
                    "display_name": "Number of Nights",
                    "aggregator": "sum",
                    "column": "nights",
                    "decimal_places": 0,
                },
                {
                    "display_name": "Distance (km)",
                    "aggregator": "sum",
                    "column": "distance_km",
                    "decimal_places": 2,
                },
                {
                    "display_name": "Number of Hours",
                    "aggregator": "sum",
                    "column": "duration_hours",
                    "decimal_places": 2,
                },
            ],
            **(params.get("staff_effort") or {}),
        )
        .call()
    )

    staff_effort_renamed = (
        task(map_columns)
        .validate()
        .set_task_instance_id("staff_effort_renamed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=staff_effort,
            rename_columns={"leader": "Officer Name"},
            raise_if_not_found=False,
            retain_columns=None,
            drop_columns=None,
            duplicate_strategy="suffix",
            **(params.get("staff_effort_renamed") or {}),
        )
        .call()
    )

    staff_effort_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("staff_effort_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=staff_effort_renamed,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": True,
                "hide_header": False,
            },
            **(params.get("staff_effort_table") or {}),
        )
        .call()
    )

    staff_effort_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("staff_effort_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=staff_effort_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="staff_effort",
            **(params.get("staff_effort_html") or {}),
        )
        .call()
    )

    staff_effort_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("staff_effort_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Staff Effort",
            data=staff_effort_html,
            **(params.get("staff_effort_sv") or {}),
        )
        .call()
    )

    patrols_by_mandate = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("patrols_by_mandate")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_table,
            groupby_cols=["mandate"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "Count",
                    "aggregator": "count",
                    "column": "patrol_id",
                    "decimal_places": None,
                }
            ],
            **(params.get("patrols_by_mandate") or {}),
        )
        .call()
    )

    patrols_by_mandate_chart = (
        task(draw_bar_chart_colored)
        .validate()
        .set_task_instance_id("patrols_by_mandate_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=patrols_by_mandate,
            category="mandate",
            colors=plot_palette,
            bar_chart_configs=[
                {
                    "column": "Count",
                    "agg_func": "sum",
                    "label": "Patrols",
                    "show_label": False,
                }
            ],
            layout_kwargs={"title": None},
            **(params.get("patrols_by_mandate_chart") or {}),
        )
        .call()
    )

    patrols_by_mandate_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("patrols_by_mandate_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=patrols_by_mandate_chart,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="patrols_by_mandate_chart",
            **(params.get("patrols_by_mandate_chart_html") or {}),
        )
        .call()
    )

    patrols_by_mandate_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("patrols_by_mandate_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Patrols by Mandate",
            data=patrols_by_mandate_chart_html,
            **(params.get("patrols_by_mandate_sv") or {}),
        )
        .call()
    )

    recreational_fishing_vessels = (
        task(filter_recreational_vessels_by_category)
        .validate()
        .set_task_instance_id("recreational_fishing_vessels")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=recreational_events_filtered,
            category="fishing",
            client=er_client,
            **(params.get("recreational_fishing_vessels") or {}),
        )
        .call()
    )

    recreational_tourism_vessels = (
        task(filter_recreational_vessels_by_category)
        .validate()
        .set_task_instance_id("recreational_tourism_vessels")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=recreational_events_filtered,
            category="tourism",
            client=er_client,
            **(params.get("recreational_tourism_vessels") or {}),
        )
        .call()
    )

    commercial_fishing_vessels = (
        task(flatten_commercial_fishing_vessels)
        .validate()
        .set_task_instance_id("commercial_fishing_vessels")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=commercial_events_filtered,
            client=er_client,
            **(params.get("commercial_fishing_vessels") or {}),
        )
        .call()
    )

    fishers_documented = (
        task(explode_commercial_fishing_fishers)
        .validate()
        .set_task_instance_id("fishers_documented")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=commercial_events_filtered,
            client=er_client,
            **(params.get("fishers_documented") or {}),
        )
        .call()
    )

    recreational_fishing_count = (
        task(dataframe_count)
        .validate()
        .set_task_instance_id("recreational_fishing_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=recreational_fishing_vessels,
            **(params.get("recreational_fishing_count") or {}),
        )
        .call()
    )

    recreational_tourism_count = (
        task(dataframe_count)
        .validate()
        .set_task_instance_id("recreational_tourism_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=recreational_tourism_vessels,
            **(params.get("recreational_tourism_count") or {}),
        )
        .call()
    )

    commercial_fishing_count = (
        task(dataframe_count)
        .validate()
        .set_task_instance_id("commercial_fishing_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=commercial_fishing_vessels,
            **(params.get("commercial_fishing_count") or {}),
        )
        .call()
    )

    vessels_documented = (
        task(assemble_vessels_documented)
        .validate()
        .set_task_instance_id("vessels_documented")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            recreational_fishing_count=recreational_fishing_count,
            commercial_fishing_count=commercial_fishing_count,
            tourism_vessel_count=recreational_tourism_count,
            **(params.get("vessels_documented") or {}),
        )
        .call()
    )

    recreational_fishing_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("recreational_fishing_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=recreational_fishing_vessels,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": True,
                "hide_header": False,
            },
            **(params.get("recreational_fishing_table") or {}),
        )
        .call()
    )

    recreational_fishing_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("recreational_fishing_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=recreational_fishing_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="recreational_fishing_vessels",
            **(params.get("recreational_fishing_html") or {}),
        )
        .call()
    )

    recreational_fishing_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("recreational_fishing_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Recreational Fishing Vessels",
            data=recreational_fishing_html,
            **(params.get("recreational_fishing_sv") or {}),
        )
        .call()
    )

    recreational_tourism_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("recreational_tourism_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=recreational_tourism_vessels,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": True,
                "hide_header": False,
            },
            **(params.get("recreational_tourism_table") or {}),
        )
        .call()
    )

    recreational_tourism_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("recreational_tourism_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=recreational_tourism_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="recreational_tourism_vessels",
            **(params.get("recreational_tourism_html") or {}),
        )
        .call()
    )

    recreational_tourism_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("recreational_tourism_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Recreational Tourism Vessels",
            data=recreational_tourism_html,
            **(params.get("recreational_tourism_sv") or {}),
        )
        .call()
    )

    commercial_fishing_vessels_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("commercial_fishing_vessels_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=commercial_fishing_vessels,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": True,
                "hide_header": False,
            },
            **(params.get("commercial_fishing_vessels_table") or {}),
        )
        .call()
    )

    commercial_fishing_vessels_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("commercial_fishing_vessels_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=commercial_fishing_vessels_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="commercial_fishing_vessels",
            **(params.get("commercial_fishing_vessels_html") or {}),
        )
        .call()
    )

    commercial_fishing_vessels_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("commercial_fishing_vessels_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Commercial Fishing Vessels Encountered",
            data=commercial_fishing_vessels_html,
            **(params.get("commercial_fishing_vessels_sv") or {}),
        )
        .call()
    )

    fishers_documented_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("fishers_documented_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=fishers_documented,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": True,
                "hide_header": False,
            },
            **(params.get("fishers_documented_table") or {}),
        )
        .call()
    )

    fishers_documented_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("fishers_documented_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=fishers_documented_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="fishers_documented",
            **(params.get("fishers_documented_html") or {}),
        )
        .call()
    )

    fishers_documented_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("fishers_documented_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Fishers Documented",
            data=fishers_documented_html,
            **(params.get("fishers_documented_sv") or {}),
        )
        .call()
    )

    vessels_documented_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("vessels_documented_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=vessels_documented,
            columns=None,
            table_config={
                "enable_sorting": False,
                "enable_filtering": False,
                "enable_download": True,
                "hide_header": False,
            },
            **(params.get("vessels_documented_table") or {}),
        )
        .call()
    )

    vessels_documented_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("vessels_documented_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=vessels_documented_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="vessels_documented",
            **(params.get("vessels_documented_html") or {}),
        )
        .call()
    )

    vessels_documented_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("vessels_documented_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Vessels Documented",
            data=vessels_documented_html,
            **(params.get("vessels_documented_sv") or {}),
        )
        .call()
    )

    vessels_by_category = (
        task(assemble_vessels_by_category)
        .validate()
        .set_task_instance_id("vessels_by_category")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            commercial_fishing_count=commercial_fishing_count,
            recreational_fishing_count=recreational_fishing_count,
            recreational_tourism_count=recreational_tourism_count,
            **(params.get("vessels_by_category") or {}),
        )
        .call()
    )

    vessels_inspected_chart = (
        task(draw_bar_chart_colored)
        .validate()
        .set_task_instance_id("vessels_inspected_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=vessels_by_category,
            category="category",
            colors=plot_palette,
            bar_chart_configs=[
                {
                    "column": "count",
                    "agg_func": "sum",
                    "label": "Vessels",
                    "show_label": False,
                }
            ],
            layout_kwargs={"title": None},
            **(params.get("vessels_inspected_chart") or {}),
        )
        .call()
    )

    vessels_inspected_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("vessels_inspected_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=vessels_inspected_chart,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="vessels_inspected_chart",
            **(params.get("vessels_inspected_chart_html") or {}),
        )
        .call()
    )

    vessels_inspected_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("vessels_inspected_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Type of Vessels Inspected",
            data=vessels_inspected_chart_html,
            **(params.get("vessels_inspected_sv") or {}),
        )
        .call()
    )

    track_colormap = (
        task(apply_qualitative_color_map)
        .validate()
        .set_task_instance_id("track_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=trajs, **(params.get("track_colormap") or {}))
        .call()
    )

    track_legend_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("track_legend_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("track_legend_title") or {}))
        .call()
    )

    commercial_events_tagged = (
        task(tag_commercial_vessel_category)
        .validate()
        .set_task_instance_id("commercial_events_tagged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=commercial_events_filtered,
            **(params.get("commercial_events_tagged") or {}),
        )
        .call()
    )

    recreational_events_tagged = (
        task(tag_recreational_vessel_category)
        .validate()
        .set_task_instance_id("recreational_events_tagged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=recreational_events_filtered,
            **(params.get("recreational_events_tagged") or {}),
        )
        .call()
    )

    events_for_map = (
        task(concat_dataframes)
        .validate()
        .set_task_instance_id("events_for_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            dfs=[commercial_events_tagged, recreational_events_tagged],
            ensure_columns=[
                "event_type_display",
                "event_category_display",
                "category",
                "id",
                "geometry",
            ],
            reset_index=True,
            **(params.get("events_for_map") or {}),
        )
        .call()
    )

    event_colormap = (
        task(apply_qualitative_color_map)
        .validate()
        .set_task_instance_id("event_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=events_for_map, **(params.get("event_colormap") or {}))
        .call()
    )

    event_legend_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("event_legend_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("event_legend_title") or {}))
        .call()
    )

    patrol_track_layer = (
        task(create_path_layer)
        .validate()
        .set_task_instance_id("patrol_track_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=track_colormap,
            legend={
                "title": track_legend_title,
                "label_column": "column_label",
                "color_column": "column_color",
            },
            data_url=None,
            tooltip_columns=[
                "extra__patrol_type__display",
                "dist_meters",
                "timespan_seconds",
            ],
            layer_style={"get_color": "column_color"},
            **(params.get("patrol_track_layer") or {}),
        )
        .call()
    )

    event_layer = (
        task(create_scatterplot_layer)
        .validate()
        .set_task_instance_id("event_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=event_colormap,
            legend={
                "title": event_legend_title,
                "label_column": "column_label",
                "color_column": "column_color",
            },
            data_url=None,
            tooltip_columns=["category"],
            layer_style={"get_fill_color": "column_color"},
            **(params.get("event_layer") or {}),
        )
        .call()
    )

    activities_layers = (
        task(drop_skipped_layers)
        .validate()
        .set_task_instance_id("activities_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            layers=[patrol_track_layer, event_layer],
            **(params.get("activities_layers") or {}),
        )
        .call()
    )

    activities_view_state = (
        task(fit_view_to_geodataframes)
        .validate()
        .set_task_instance_id("activities_view_state")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=activities_layers, **(params.get("activities_view_state") or {})
        )
        .call()
    )

    activities_map = (
        task(draw_map)
        .validate()
        .set_task_instance_id("activities_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=activities_layers,
            tile_layers=base_maps,
            static=False,
            title=None,
            view_state=activities_view_state,
            max_zoom=17,
            legend_style={"placement": "bottom-right"},
            output_type="html",
            **(params.get("activities_map") or {}),
        )
        .call()
    )

    activities_map_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("activities_map_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=activities_map,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="activities_map.html",
            filename_suffix=None,
            **(params.get("activities_map_url") or {}),
        )
        .call()
    )

    activities_map_sv = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("activities_map_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Map of Activities Documented",
            data=activities_map_url,
            **(params.get("activities_map_sv") or {}),
        )
        .call()
    )

    download_attachments = (
        task(download_event_attachments)
        .validate()
        .set_task_instance_id("download_attachments")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            event_gdf=event_colormap,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            attachments_subdir="attachments",
            use_index_as_id=False,
            **(params.get("download_attachments") or {}),
        )
        .call()
    )

    activities_map_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("activities_map_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=activities_map_url,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"full_page": False},
            **(params.get("activities_map_png") or {}),
        )
        .call()
    )

    patrols_by_mandate_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("patrols_by_mandate_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=patrols_by_mandate_chart_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"full_page": False},
            **(params.get("patrols_by_mandate_png") or {}),
        )
        .call()
    )

    vessels_inspected_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("vessels_inspected_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=vessels_inspected_chart_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"full_page": False},
            **(params.get("vessels_inspected_png") or {}),
        )
        .call()
    )

    report_template_path = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("report_template_path")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("report_template_path") or {}))
        .call()
    )

    generated_by = (
        task(get_report_generated_by)
        .validate()
        .set_task_instance_id("generated_by")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client, **(params.get("generated_by") or {}))
        .call()
    )

    patrol_report = (
        task(generate_belize_patrol_report)
        .validate()
        .set_task_instance_id("patrol_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            template_path=report_template_path,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            generated_by=generated_by,
            time_range=time_range,
            patrol_effort_summary=patrol_effort_summary,
            staff_effort=staff_effort_renamed,
            vessels_documented=vessels_documented,
            recreational_fishing_vessels=recreational_fishing_vessels,
            recreational_tourism_vessels=recreational_tourism_vessels,
            commercial_fishing_vessels=commercial_fishing_vessels,
            fishers_documented=fishers_documented,
            patrols_by_mandate_chart_png=patrols_by_mandate_png,
            vessels_inspected_chart_png=vessels_inspected_png,
            activities_map_png=activities_map_png,
            photo_attachment_paths=download_attachments,
            photo_events=event_colormap,
            **(params.get("patrol_report") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_belize_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                pes_patrols_sv,
                pes_distance_sv,
                pes_nights_sv,
                pes_hours_sv,
                pes_fuel_sv,
                staff_effort_sv,
                patrols_by_mandate_sv,
                vessels_inspected_sv,
                vessels_documented_sv,
                recreational_fishing_sv,
                recreational_tourism_sv,
                commercial_fishing_vessels_sv,
                fishers_documented_sv,
                activities_map_sv,
            ],
            groupers=groupers,
            time_range=time_range,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
