"""
Belize / Fisheries Dept - build & populate the docx report from the SAME
outputs generate_report_outputs.py already produced.

Takes the tables in .scripts/output/tables/ and screenshots the actual
charts/map generate_report_outputs.py already rendered (.scripts/output/
charts/*.html, .scripts/output/map.html - built with the real
ecoscope.plotting bar_chart function and the real
create_point_layer/create_polyline_layer/draw_ecomap functions, same as
every other workflow in this org), via a headless Chromium (Playwright,
already present in this pixi env - confirmed working, no new dependency).

This deliberately does NOT re-derive a second, different-looking set of
charts/map (e.g. via matplotlib) - that was tried once and rejected: the
docx should show the same outputs as the dashboard, not a look-alike.

Produces a fully populated .docx matching EXACTLY the source PDF's own section
layout, no additions: title/background block, the same 4-field metadata block
(Report Generated by/on, Report Start/End Date - from report_meta.csv), Patrol
Effort Summary, Staff Effort, a Patrols by Mandate chart (no table under it -
the PDF shows this chart alone), a Type of Vessels Inspected chart, Vessels
Documented, Recreational Fishing Vessels, Recreational Tourism Vessels,
Commercial Fishing Vessels Encountered, Fishers Documented, and the map.
(Joint Patrol Team is also in the source PDF but has no matching event type on
this account at all - see the PRD's open question #4 - so it's left out
rather than faked empty.)

One thing this deliberately does NOT do, tied to an open PRD question: it does
NOT title the report, or name the output file, "South Water Caye Marine
Reserve" / SWCMR. The PRD's "Multi-site scope" note found that this account's
actual patrol activity in this window is geographically from a different area
(Corozal Bay / Shipstern), and there is no site/station field anywhere in the
schema to confirm which reserve these patrols belong to. Labeling it SWCMR
would be fabricating a fact the data doesn't support - the source PDF is only
the example being replicated, not this report's actual site.

"Report Generated by" IS populated now (unlike an earlier version of this
script) - via the same get_user_me pattern APN's patrol_event workflow uses
(client._get("user/me"), the ER account that actually ran the pipeline), not
a guess at the PDF's "Julio Maaz" (whoever ran SMART's own export - not
something this account/pipeline can know or reproduce).

This directly populates the docx with real data (not a docxtpl Jinja2
template with {{ placeholders }}) - a template-based version, following the
curacao-nest_hatching/.scripts/build_report_template.py pattern, is the
right shape for the eventual production workflow (where spec.yaml renders it
via docxtpl on every run), but this script's job right now is to prove the
populated report is achievable end to end from real data.

Run with (after generate_report_outputs.py has already been run once):
  cd /Users/zak/Documents/w-dynamics/ICMBio-patrol_analysis/ecoscope-workflows-patrol-analysis-workflow
  pixi run --locked -e default python ../../belize-patrol_report/.scripts/build_docx_report.py
"""

from pathlib import Path

import pandas as pd
from docx import Document
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor
from playwright.sync_api import sync_playwright

SCRIPT_DIR = Path(__file__).parent
OUT_DIR = SCRIPT_DIR / "output"
TABLES_DIR = OUT_DIR / "tables"
CHARTS_DIR = OUT_DIR / "charts"
MAP_HTML = OUT_DIR / "map.html"
IMAGES_DIR = OUT_DIR / "docx_images"
IMAGES_DIR.mkdir(parents=True, exist_ok=True)
DOCX_PATH = OUT_DIR / "belize_patrol_report.docx"

HEADING_FONT = "Georgia"
BODY_FONT = "Calibri"
BLACK = RGBColor(0, 0, 0)
HEADER_FILL_HEX = "B7DFCB"  # light teal/mint, matching the source PDF's table header shading

# (html source, output png, viewport, extra wait for JS-rendered content)
SCREENSHOTS = [
    (CHARTS_DIR / "patrols_by_mandate.html", IMAGES_DIR / "patrols_by_mandate.png", (900, 500), 800),
    (CHARTS_DIR / "vessels_by_category.html", IMAGES_DIR / "vessels_by_category.png", (700, 600), 800),
    (MAP_HTML, IMAGES_DIR / "map.png", (1300, 800), 8000),  # deck.gl/lonboard - satellite basemap tiles take a while to actually paint in after "load" fires; wide enough that the title doesn't wrap
]


def hr(n, title):
    print("\n" + "=" * 78)
    print(f"STEP {n}: {title}")
    print("=" * 78)


def _style_run(run, font=None, size=None, bold=None, color=BLACK):
    if font:
        run.font.name = font
        rPr = run._element.get_or_add_rPr()
        rFonts = rPr.find(qn("w:rFonts"))
        if rFonts is None:
            rFonts = rPr.makeelement(qn("w:rFonts"), {})
            rPr.append(rFonts)
        rFonts.set(qn("w:ascii"), font)
        rFonts.set(qn("w:hAnsi"), font)
    if size:
        run.font.size = Pt(size)
    if bold is not None:
        run.font.bold = bold
    if color is not None:
        run.font.color.rgb = color
    return run


def _shade_cell(cell, hex_color):
    tcPr = cell._tc.get_or_add_tcPr()
    shd = tcPr.makeelement(qn("w:shd"), {qn("w:val"): "clear", qn("w:color"): "auto", qn("w:fill"): hex_color})
    tcPr.append(shd)


def _clean_cell_text(v) -> str:
    if pd.isna(v):
        return ""
    s = str(v)
    if s.startswith("[") and s.endswith("]"):
        s = s.strip("[]").replace("'", "")
    return s


def _heading(doc, text, size=16):
    p = doc.add_paragraph()
    _style_run(p.add_run(text), font=HEADING_FONT, size=size, bold=True)
    return p


def _add_table(doc, df: pd.DataFrame, empty_note="No records in this period."):
    if df is None or not len(df):
        p = doc.add_paragraph()
        _style_run(p.add_run(empty_note), font=BODY_FONT, size=10, bold=False)
        return
    table = doc.add_table(rows=1, cols=len(df.columns))
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    for i, col in enumerate(df.columns):
        cell = table.rows[0].cells[i]
        _shade_cell(cell, HEADER_FILL_HEX)
        p = cell.paragraphs[0]
        _style_run(p.add_run(col.replace("_", " ").title()), font=BODY_FONT, size=9, bold=True)
    for _, row in df.iterrows():
        cells = table.add_row().cells
        for i, col in enumerate(df.columns):
            p = cells[i].paragraphs[0]
            _style_run(p.add_run(_clean_cell_text(row[col])), font=BODY_FONT, size=9)


def _add_image(doc, path, width_in=6.0):
    if not path.exists():
        p = doc.add_paragraph()
        _style_run(p.add_run(f"[missing: {path.name}]"), font=BODY_FONT, size=10)
        return
    doc.add_picture(str(path), width=Inches(width_in))
    doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER


# ---------------------------------------------------------------------------
hr(1, "Load tables written by generate_report_outputs.py")
tables = {}
for name in [
    "report_meta",
    "01_patrol_effort_summary",
    "02_staff_effort",
    "03_patrols_by_mandate",
    "04_vessels_documented",
    "05_recreational_fishing_vessels",
    "06_recreational_tourism_vessels",
    "07_commercial_fishing_vessels_encountered",
    "08_fishers_documented",
]:
    path = TABLES_DIR / f"{name}.csv"
    if not path.exists():
        raise FileNotFoundError(f"{path} not found - run generate_report_outputs.py first")
    tables[name] = pd.read_csv(path)
    print(f"  {name}: {len(tables[name])} rows")

# ---------------------------------------------------------------------------
hr(2, "Screenshot the SAME charts/map generate_report_outputs.py already rendered")
missing = [src for src, _, _, _ in SCREENSHOTS if not src.exists()]
if missing:
    raise FileNotFoundError(f"Missing HTML outputs, run generate_report_outputs.py first: {missing}")

with sync_playwright() as p:
    browser = p.chromium.launch()
    for src, dst, (w, h), wait_ms in SCREENSHOTS:
        page = browser.new_page(viewport={"width": w, "height": h})
        page.goto(src.resolve().as_uri())
        # "networkidle" hangs on the map: basemap tile layers keep streaming requests
        # at some zoom levels and never go fully idle, so this waits for the more
        # basic "load" event only and then just a fixed pause for JS rendering -
        # reliable for both the plotly charts and the deck.gl map.
        page.wait_for_load_state("load")
        page.wait_for_timeout(wait_ms)
        page.screenshot(path=str(dst))
        page.close()
        print(f"  {src.name} -> {dst.name}")
    browser.close()

# ---------------------------------------------------------------------------
hr(3, "Build the docx")
doc = Document()

title = doc.add_paragraph()
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
_style_run(title.add_run("Belize Fisheries Department"), font=HEADING_FONT, size=24, bold=True)

subtitle = doc.add_paragraph()
subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
_style_run(subtitle.add_run("Patrol & Vessel Monitoring Report"), font=HEADING_FONT, size=16)

# Deliberately not "South Water Caye Marine Reserve" - see this script's docstring
# and PRD open question #6 (no site/station field exists to confirm which reserve
# this account's patrol activity actually belongs to).
site_note = doc.add_paragraph()
site_note.alignment = WD_ALIGN_PARAGRAPH.CENTER
_style_run(
    site_note.add_run("Site: [pending - see PRD open question #6; account covers more than one protected area]"),
    font=BODY_FONT, size=10, bold=False,
)

# Same 2-line layout as the source PDF's own metadata block. "Report Generated by" is
# the ER account that actually ran this pipeline (APN's get_user_me pattern - see
# generate_report_outputs.py) - not the PDF's "Julio Maaz", which is whoever ran
# SMART's own export and isn't something this account/pipeline can know or reproduce.
report_meta = tables["report_meta"].iloc[0]
meta1 = doc.add_paragraph()
meta1.alignment = WD_ALIGN_PARAGRAPH.CENTER
_style_run(meta1.add_run(f"Report Generated by: {report_meta['generated_by']}    "), font=BODY_FONT, size=11)
_style_run(meta1.add_run(f"Report Generated on: {report_meta['generated_on']}"), font=BODY_FONT, size=11)
meta2 = doc.add_paragraph()
meta2.alignment = WD_ALIGN_PARAGRAPH.CENTER
_style_run(meta2.add_run(f"Report Start Date: {report_meta['report_start_date']}    "), font=BODY_FONT, size=11)
_style_run(meta2.add_run(f"Report End Date: {report_meta['report_end_date']}"), font=BODY_FONT, size=11)

doc.add_paragraph()

_heading(doc, "Patrol Effort Summary")
_add_table(doc, tables["01_patrol_effort_summary"])

_heading(doc, "Staff Effort")
_add_table(doc, tables["02_staff_effort"])

# Chart only, no table beneath it - the source PDF shows "Patrols by Mandate" as a
# chart alone, same as its "Type of Vessels Inspected" chart below.
_heading(doc, "Patrols by Mandate")
_add_image(doc, IMAGES_DIR / "patrols_by_mandate.png")

_heading(doc, "Type of Vessels Inspected")
_add_image(doc, IMAGES_DIR / "vessels_by_category.png", width_in=4.5)

_heading(doc, "Vessels Documented")
_add_table(doc, tables["04_vessels_documented"])

_heading(doc, "Recreational Fishing Vessels")
_add_table(doc, tables["05_recreational_fishing_vessels"])

_heading(doc, "Recreational Tourism Vessels")
_add_table(doc, tables["06_recreational_tourism_vessels"])

_heading(doc, "Commercial Fishing Vessels Encountered")
_add_table(doc, tables["07_commercial_fishing_vessels_encountered"])

_heading(doc, "Fishers Documented")
_add_table(doc, tables["08_fishers_documented"])

_heading(doc, "Map of Activities Documented")
_add_image(doc, IMAGES_DIR / "map.png", width_in=6.0)

doc.save(DOCX_PATH)
print(f"\nwrote {DOCX_PATH}")

hr(4, "Done")
